//! SQLite state store at `.redom/redo-msh.db`.
//!
//! Journal mode is chosen per filesystem: WAL (many readers + one writer, the
//! parallel peer model's preferred mode) on ordinary local disks, and PERSIST
//! (rollback journal) on filesystems where WAL's shared-memory mmap cannot
//! work — WSL drvfs/9p and FUSE (see `fsguard`). `REDO_JOURNAL_MODE=wal` or
//! `=persist` overrides the detection. A database left in WAL format by a
//! build on another filesystem is converted transparently on open.
//!
//! Two tables (see plan):
//!   * `files` — per-file stamp cache for *all* files (sources and targets).
//!     Equality is always by `csum` (blake3); `mtime`/`size` only gate whether
//!     we must recompute the hash.
//!   * `deps`  — dependency edges. The `csum` recorded here is the equality
//!     basis for change detection; `mtime`/`size` are fast-path accelerators.
//!
//! A `meta` table holds the schema version and the monotonic `runid` build
//! counter (clock-independent).

use anyhow::{Context, Result};
use rusqlite::{Connection, OptionalExtension};
use std::path::{Path, PathBuf};
use std::time::Duration;

const BUSY_TIMEOUT: Duration = Duration::from_secs(60);

/// Bump whenever the on-disk schema changes incompatibly. The `.redom` database
/// is a pure cache (everything in it can be regenerated by rebuilding), so a
/// mismatch is resolved by wiping and rebuilding rather than migrating.
pub const SCHEMA_VERSION: i64 = 4;

/// Dependency edge kinds.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i64)]
pub enum DepKind {
    IfChange = 0,
    IfCreate = 1,
    Always = 2,
    DoFile = 3,
    /// Marker recorded when a build starts and removed only after the target
    /// commits successfully. If it is present outside a build, the last build
    /// failed (or crashed) and the target is unconditionally out of date —
    /// a leftover output file from an earlier success must not be trusted.
    Uncommitted = 4,
}

impl DepKind {
    pub fn from_i64(v: i64) -> Option<DepKind> {
        match v {
            0 => Some(DepKind::IfChange),
            1 => Some(DepKind::IfCreate),
            2 => Some(DepKind::Always),
            3 => Some(DepKind::DoFile),
            4 => Some(DepKind::Uncommitted),
            _ => None,
        }
    }
}

/// Open (creating if needed) the database and apply pragmas + schema.
///
/// If an existing database was written by a redo-msh with a different
/// `SCHEMA_VERSION`, it is wiped and recreated: the database is a regenerable
/// cache, so rebuilding is always safe (the next build just does more work
/// once). This avoids silently misreading an incompatible layout.
pub fn open(db_path: &Path) -> Result<Connection> {
    let mode = choose_journal_mode(db_path);
    if mode == JournalMode::Persist {
        // A WAL-format database cannot even be read here (its shared-memory
        // map fails), so this must happen before the version probe below.
        convert_from_wal_if_needed(db_path)?;
    }
    if let Some(found) = incompatible_version(db_path)? {
        eprintln!(
            "redo-msh: .redom database schema v{found} != v{SCHEMA_VERSION}; \
             rebuilding build state"
        );
        wipe(db_path);
    }
    let conn = Connection::open(db_path)
        .with_context(|| format!("opening database {}", db_path.display()))?;
    apply_pragmas(&conn, mode)?;
    init_schema(&conn)?;
    Ok(conn)
}

/// Journal mode for the state database. WAL is preferred (readers and the
/// writer never block each other); PERSIST is the fallback for filesystems
/// where WAL's `-shm` mmap cannot work.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum JournalMode {
    Wal,
    Persist,
}

/// Pick the journal mode for `db_path`: `REDO_JOURNAL_MODE` if set (an escape
/// hatch, and the way to exercise the PERSIST path in tests on any FS),
/// otherwise by classifying the filesystem under the database's directory.
/// A pure function of environment + path, so every concurrent redo-msh
/// process computes the same answer for the same database.
fn choose_journal_mode(db_path: &Path) -> JournalMode {
    if let Ok(v) = std::env::var("REDO_JOURNAL_MODE") {
        match v.to_ascii_lowercase().as_str() {
            "wal" => return JournalMode::Wal,
            "persist" => return JournalMode::Persist,
            _ => eprintln!(
                "redo-msh: warning: ignoring REDO_JOURNAL_MODE={v:?} \
                 (expected 'wal' or 'persist')"
            ),
        }
    }
    // Cached per process: every task thread opens its own connection, and
    // the filesystem under one database does not change mid-run.
    static KIND: std::sync::OnceLock<crate::fsguard::FsKind> = std::sync::OnceLock::new();
    let dir = db_path.parent().unwrap_or_else(|| Path::new("."));
    match KIND.get_or_init(|| crate::fsguard::classify(dir)) {
        crate::fsguard::FsKind::MmapUnsafe => JournalMode::Persist,
        _ => JournalMode::Wal,
    }
}

/// Whether the file at `db_path` is an SQLite database whose header says it
/// is in WAL format (read/write format version 2). Read directly from the
/// header because opening a WAL database through SQLite is exactly what
/// fails on an mmap-unsafe filesystem.
fn is_wal_format(db_path: &Path) -> bool {
    use std::io::Read;
    let mut header = [0u8; 20];
    match std::fs::File::open(db_path).and_then(|mut f| f.read_exact(&mut header)) {
        Ok(()) => header[..16] == *b"SQLite format 3\0" && (header[18] == 2 || header[19] == 2),
        Err(_) => false,
    }
}

/// Convert a WAL-format database to rollback-journal format in place. Needed
/// when a database built on an ordinary disk moves to an mmap-unsafe
/// filesystem: WAL there fails in `xShmMap` before any query can run. With
/// `locking_mode=EXCLUSIVE` set first, SQLite runs WAL against heap-backed
/// shared memory (no `-shm` mmap), which lets the `journal_mode` change
/// checkpoint the WAL and rewrite the header. Racing processes serialize on
/// the exclusive lock; the losers then find the work already done (their
/// `journal_mode` change is a no-op).
fn convert_from_wal_if_needed(db_path: &Path) -> Result<()> {
    if !is_wal_format(db_path) {
        return Ok(());
    }
    eprintln!(
        "redo-msh: {} is in WAL format, which this filesystem cannot support; \
         converting to rollback-journal format",
        db_path.display()
    );
    let conn = Connection::open(db_path)
        .with_context(|| format!("opening database {} for conversion", db_path.display()))?;
    conn.busy_timeout(BUSY_TIMEOUT)?;
    conn.pragma_update(None, "locking_mode", "EXCLUSIVE")?;
    conn.pragma_update(None, "journal_mode", "PERSIST")
        .with_context(|| format!("converting {} out of WAL mode", db_path.display()))?;
    // Dropping the connection releases the exclusive lock.
    Ok(())
}

/// If `db_path` exists and records a schema version different from the current
/// one, return that version. Returns `None` for a fresh database, a database
/// with no recorded version, or a version match.
fn incompatible_version(db_path: &Path) -> Result<Option<i64>> {
    if !db_path.exists() {
        return Ok(None);
    }
    let conn = Connection::open(db_path)
        .with_context(|| format!("opening database {}", db_path.display()))?;
    let has_meta = conn
        .query_row(
            "SELECT 1 FROM sqlite_master WHERE type='table' AND name='meta'",
            [],
            |_| Ok(()),
        )
        .optional()?
        .is_some();
    if !has_meta {
        return Ok(None);
    }
    let version: Option<i64> = conn
        .query_row(
            "SELECT value FROM meta WHERE key = 'schema_version'",
            [],
            |r| r.get(0),
        )
        .optional()?;
    // `conn` is dropped here, releasing the file before the caller wipes it.
    Ok(match version {
        Some(v) if v != SCHEMA_VERSION => Some(v),
        _ => None,
    })
}

/// Remove the database and its sidecar files (both journal modes).
fn wipe(db_path: &Path) {
    let _ = std::fs::remove_file(db_path);
    let _ = std::fs::remove_file(sidecar(db_path, "-wal"));
    let _ = std::fs::remove_file(sidecar(db_path, "-shm"));
    let _ = std::fs::remove_file(sidecar(db_path, "-journal"));
}

fn sidecar(db_path: &Path, suffix: &str) -> PathBuf {
    let mut s = db_path.as_os_str().to_os_string();
    s.push(suffix);
    PathBuf::from(s)
}

fn apply_pragmas(conn: &Connection, mode: JournalMode) -> Result<()> {
    // The busy handler must be set before journal_mode: the mode change
    // itself takes locks and can contend with concurrent peers. A custom
    // handler with a short fixed sleep replaces SQLite's default
    // millisecond-scale backoff: under the parallel engine many short
    // write transactions collide constantly, and paying 1-25ms per
    // collision serializes the build far below the database's actual
    // throughput. 200µs x 300k retries preserves the 60s overall budget.
    conn.busy_handler(Some(|count| {
        std::thread::sleep(std::time::Duration::from_micros(200));
        (count as u64) < BUSY_TIMEOUT.as_micros() as u64 / 200
    }))?;
    match mode {
        JournalMode::Wal => {
            // WAL: many readers + one writer; preferred for the parallel peer
            // model. synchronous=NORMAL is safe in WAL: power loss can drop
            // the last commit (causing a safe rebuild) but never corrupts.
            conn.pragma_update(None, "journal_mode", "WAL")?;
            conn.pragma_update(None, "synchronous", "NORMAL")?;
        }
        JournalMode::Persist => {
            // Rollback journal for mmap-unsafe filesystems (WSL drvfs/9p,
            // FUSE). PERSIST avoids journal create/delete churn per commit.
            // synchronous must be FULL here: unlike WAL, NORMAL in rollback
            // mode leaves a window where power loss can corrupt the database.
            conn.pragma_update(None, "journal_mode", "PERSIST")?;
            conn.pragma_update(None, "synchronous", "FULL")?;
        }
    }
    conn.pragma_update(None, "foreign_keys", "ON")?;
    Ok(())
}

/// Run `f` inside an `BEGIN IMMEDIATE` transaction, committing on success and
/// rolling back on error.
///
/// All multi-statement write sequences must go through this. IMMEDIATE takes
/// the write lock up front, so lock acquisition happens at `BEGIN` — where the
/// busy timeout applies — rather than on the first write inside a read
/// transaction, where SQLite returns `SQLITE_BUSY` immediately (waiting there
/// could deadlock two upgrading readers). This matters in both journal modes
/// (WAL still has a single writer) and doubly under PERSIST, where readers
/// and the writer also contend.
pub fn write_txn<T>(conn: &Connection, f: impl FnOnce(&Connection) -> Result<T>) -> Result<T> {
    let tx = rusqlite::Transaction::new_unchecked(conn, rusqlite::TransactionBehavior::Immediate)?;
    let out = f(&tx)?;
    tx.commit()?;
    Ok(out)
}

fn init_schema(conn: &Connection) -> Result<()> {
    conn.execute_batch(
        r#"
        CREATE TABLE IF NOT EXISTS meta (
            key   TEXT PRIMARY KEY,
            value INTEGER NOT NULL
        );

        -- Path columns use COLLATE NOCASE so identity is case-insensitive,
        -- matching NTFS semantics and keeping one row per file when a project
        -- is shared between Windows and WSL. Original case is preserved in the
        -- stored text (used for filesystem I/O); only comparison is folded.
        CREATE TABLE IF NOT EXISTS files (
            path     TEXT PRIMARY KEY COLLATE NOCASE, -- root-relative, '/' separators
            dofile   TEXT,               -- .do file used (root-relative); NULL = source file
            built_at INTEGER,            -- unix nanos of last successful build (targets only)
            mtime    INTEGER,            -- last-observed mtime (unix nanos)
            size     INTEGER,            -- last-observed size in bytes
            csum     TEXT,               -- last-observed blake3 content hash (hex)
            runid    INTEGER             -- build counter when last verified/built
        );

        CREATE TABLE IF NOT EXISTS deps (
            target TEXT NOT NULL COLLATE NOCASE, -- dependent target (root-relative)
            kind   INTEGER NOT NULL,     -- DepKind: 0 ifchange, 1 ifcreate, 2 always, 3 dofile, 4 uncommitted
            dep    TEXT COLLATE NOCASE,  -- dependency path (ifchange/ifcreate/dofile); NULL for always
            csum   TEXT,                 -- dep content hash expected at build time (equality basis)
            mtime  INTEGER,              -- recorded mtime (fast-path accelerator)
            size   INTEGER,              -- recorded size (fast-path accelerator)
            PRIMARY KEY (target, kind, dep)
        );

        CREATE INDEX IF NOT EXISTS deps_by_target ON deps(target);

        -- The shared waits-for graph (see waits.rs), implementing the
        -- machine verified in verification/SpeculationMP.tla: one row per
        -- live wait edge "some traversal of `waiter` is blocked until
        -- `dep` settles". Every settle-wait is here (rule R1) — checker
        -- waits, speculative-spawn creation edges (which make drain waits
        -- visible), and running-do-file demands — and cycle detection is a
        -- reachability query run atomically with the insert. `kind` types
        -- the edge (rule R2): 0 = hard demand (a running do-file's
        -- redo-ifchange), 1 = soft checker wait, 2 = soft creation edge.
        -- Cycles that ride a soft edge are resolved by evicting the
        -- speculation, never by failing the demand (rule R3). Paths are
        -- stored pre-lowercased (the graph only needs identity, and BINARY
        -- comparison keeps the recursive CTE collation-exact). `owner`
        -- identifies the inserting process and is tied to a kernel
        -- liveness lock, so edges from dead processes can be
        -- garbage-collected. Edges are transient state, deliberately not
        -- scoped to a session: two concurrent redo invocations share the
        -- same target locks, so a cross-session wait cycle is a real
        -- deadlock and must be visible in one graph.
        CREATE TABLE IF NOT EXISTS waits (
            waiter  TEXT NOT NULL,
            dep     TEXT NOT NULL,
            owner   TEXT NOT NULL,
            kind    INTEGER NOT NULL,
            PRIMARY KEY (waiter, dep, owner)
        );

        CREATE INDEX IF NOT EXISTS waits_by_owner ON waits(owner);
        CREATE INDEX IF NOT EXISTS waits_by_dep ON waits(dep);
        "#,
    )
    .context("initializing schema")?;

    conn.execute(
        "INSERT OR IGNORE INTO meta(key, value) VALUES ('schema_version', ?1)",
        [SCHEMA_VERSION],
    )?;
    conn.execute(
        "INSERT OR IGNORE INTO meta(key, value) VALUES ('runid', 0)",
        [],
    )?;
    Ok(())
}

/// Atomically increment and return the global build counter. A single
/// UPDATE…RETURNING statement, so two concurrent processes can never read
/// each other's increment (the old UPDATE-then-SELECT pair could).
pub fn next_runid(conn: &Connection) -> Result<i64> {
    let runid: i64 = conn.query_row(
        "UPDATE meta SET value = value + 1 WHERE key = 'runid' RETURNING value",
        [],
        |r| r.get(0),
    )?;
    Ok(runid)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn paths_are_case_insensitive() {
        let dir = std::env::temp_dir().join(format!("redo-msh-dbtest-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let conn = open(&dir.join("t.db")).unwrap();

        conn.execute("INSERT INTO files(path) VALUES ('App.txt')", [])
            .unwrap();
        // A different-cased lookup matches (NOCASE collation).
        let found: i64 = conn
            .query_row(
                "SELECT count(*) FROM files WHERE path = ?1",
                ["app.txt"],
                |r| r.get(0),
            )
            .unwrap();
        assert_eq!(found, 1);

        // A different-cased insert collapses onto the same primary key.
        conn.execute("INSERT OR REPLACE INTO files(path) VALUES ('APP.TXT')", [])
            .unwrap();
        let total: i64 = conn
            .query_row("SELECT count(*) FROM files", [], |r| r.get(0))
            .unwrap();
        assert_eq!(total, 1, "different casings must collapse to one row");

        // Original case is preserved in storage (for filesystem I/O).
        let stored: String = conn
            .query_row("SELECT path FROM files LIMIT 1", [], |r| r.get(0))
            .unwrap();
        assert!(stored.chars().any(|c| c.is_ascii_uppercase()));

        drop(conn);
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn incompatible_schema_is_rebuilt() {
        let dir = std::env::temp_dir().join(format!(
            "redo-msh-dbver-{}-{}",
            std::process::id(),
            "mismatch"
        ));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("t.db");

        // Create a database, add a row, then fake an older schema version.
        {
            let conn = open(&path).unwrap();
            conn.execute("INSERT INTO files(path) VALUES ('stale.txt')", [])
                .unwrap();
            conn.execute(
                "UPDATE meta SET value = 1 WHERE key = 'schema_version'",
                [],
            )
            .unwrap();
        }

        // Reopening detects the mismatch and rebuilds from scratch.
        let conn = open(&path).unwrap();
        let version: i64 = conn
            .query_row("SELECT value FROM meta WHERE key='schema_version'", [], |r| {
                r.get(0)
            })
            .unwrap();
        assert_eq!(version, SCHEMA_VERSION);
        let rows: i64 = conn
            .query_row("SELECT count(*) FROM files", [], |r| r.get(0))
            .unwrap();
        assert_eq!(rows, 0, "stale data must be wiped on a schema mismatch");

        drop(conn);
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn wal_database_converts_to_rollback_journal() {
        let dir = std::env::temp_dir().join(format!("redo-msh-walconv-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("t.db");

        // Create a WAL database with a row in it (open() defaults to WAL on
        // a normal local filesystem).
        {
            let conn = open(&path).unwrap();
            conn.execute("INSERT INTO files(path) VALUES ('kept.txt')", [])
                .unwrap();
        }
        assert!(is_wal_format(&path), "fresh db should be in WAL format");

        // Convert as the mmap-unsafe open path would, then reopen in PERSIST
        // mode: data must survive and the header must no longer say WAL.
        convert_from_wal_if_needed(&path).unwrap();
        assert!(!is_wal_format(&path), "conversion must rewrite the header");

        let conn = Connection::open(&path).unwrap();
        apply_pragmas(&conn, JournalMode::Persist).unwrap();
        let mode: String = conn
            .query_row("PRAGMA journal_mode", [], |r| r.get(0))
            .unwrap();
        assert_eq!(mode.to_ascii_lowercase(), "persist");
        let rows: i64 = conn
            .query_row("SELECT count(*) FROM files", [], |r| r.get(0))
            .unwrap();
        assert_eq!(rows, 1, "data must survive the WAL conversion");

        // Converting an already-converted database is a no-op.
        drop(conn);
        convert_from_wal_if_needed(&path).unwrap();

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn persist_mode_full_open_works() {
        let dir = std::env::temp_dir().join(format!("redo-msh-persist-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("t.db");

        let conn = Connection::open(&path).unwrap();
        apply_pragmas(&conn, JournalMode::Persist).unwrap();
        init_schema(&conn).unwrap();

        let sync: i64 = conn
            .query_row("PRAGMA synchronous", [], |r| r.get(0))
            .unwrap();
        assert_eq!(sync, 2, "PERSIST mode must run synchronous=FULL");

        assert_eq!(next_runid(&conn).unwrap(), 1);
        assert_eq!(next_runid(&conn).unwrap(), 2);

        drop(conn);
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn write_txn_rolls_back_on_error() {
        let dir = std::env::temp_dir().join(format!("redo-msh-txn-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let conn = open(&dir.join("t.db")).unwrap();

        let result: Result<()> = write_txn(&conn, |c| {
            c.execute("INSERT INTO files(path) VALUES ('ghost.txt')", [])?;
            anyhow::bail!("boom");
        });
        assert!(result.is_err());
        let rows: i64 = conn
            .query_row("SELECT count(*) FROM files", [], |r| r.get(0))
            .unwrap();
        assert_eq!(rows, 0, "a failed write_txn must leave no partial writes");

        let committed: i64 = write_txn(&conn, |c| {
            c.execute("INSERT INTO files(path) VALUES ('real.txt')", [])?;
            Ok(1)
        })
        .unwrap();
        assert_eq!(committed, 1);
        let rows: i64 = conn
            .query_row("SELECT count(*) FROM files", [], |r| r.get(0))
            .unwrap();
        assert_eq!(rows, 1);

        drop(conn);
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn matching_schema_preserves_data() {
        let dir = std::env::temp_dir().join(format!(
            "redo-msh-dbver-{}-{}",
            std::process::id(),
            "match"
        ));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("t.db");

        {
            let conn = open(&path).unwrap();
            conn.execute("INSERT INTO files(path) VALUES ('keep.txt')", [])
                .unwrap();
        }
        // Same version: data survives the reopen.
        let conn = open(&path).unwrap();
        let rows: i64 = conn
            .query_row("SELECT count(*) FROM files", [], |r| r.get(0))
            .unwrap();
        assert_eq!(rows, 1, "data must persist when the schema version matches");

        drop(conn);
        let _ = std::fs::remove_dir_all(&dir);
    }
}
